apiVersion: v1
kind: Service
metadata:
  name: predictor-exporter
  namespace: model
  labels:
    app: predictor-exporter
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9101
      targetPort: 9101
  selector:
    app: predictor-exporter