apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          command: ["mlflow"]
          args:
            - server
            - --host=0.0.0.0
            - --port=5000
            - --backend-store-uri=postgresql://mlflow:mlflow@mlflow-postgresql.mlflow.svc.cluster.local:5432/mlflow
            - --serve-artifacts
            - --artifacts-destination=s3://datalake/mlflow
            - --default-artifact-root=s3://datalake/mlflow
            - --allowed-hosts=*
            - --cors-allowed-origins=*
          env:
            - name: MLFLOW_VERSION
              value: "3.5.1"
            - name: MLFLOW_ALLOWED_HOSTS
              value: "*"
            - name: MLFLOW_CORS_ALLOWED_ORIGINS
              value: "*"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: http://minio.minio.svc.cluster.local:9000
            - name: MLFLOW_ARTIFACT_ROOT
              value: s3://datalake/mlflow
            - name: MLFLOW_ARTIFACTS_DESTINATION   # thêm dòng này
              value: s3://datalake/mlflow
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-cred
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-cred
                  key: AWS_SECRET_ACCESS_KEY
          ports:
            - containerPort: 5000
