mapiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-postgres-pvc
  namespace: mlflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-postgresql
  namespace: mlflow
spec:
  selector:
    matchLabels:
      app: mlflow-postgresql
  template:
    metadata:
      labels:
        app: mlflow-postgresql
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: mlflow
            - name: POSTGRES_PASSWORD
              value: mlflow
            - name: POSTGRES_DB
              value: mlflow
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mlflow-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-postgresql
  namespace: mlflow
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: mlflow-postgresql
