apiVersion: batch/v1
kind: CronJob
metadata:
  name: locust-18h0h
  namespace: loadtest
spec:
  schedule: "0 18 * * *"   # chạy lúc 18:00 hàng ngày
  timeZone: "Asia/Ho_Chi_Minh"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: locust
              image: locustio/locust:2.31.3
              command: ["locust"]
              args:
                [
                  "-f", "/mnt/locust/locustfile.py",
                  "--headless",
                  "-u", "1800", "-r", "25",
                  "--run-time", "6h",
                  "--host", "http://api-gateway.apps.svc.cluster.local:8888"
                ]
              env:
                - name: STOP_HOUR
                  value: "0"
                - name: PROM_URL
                  value: "http://prometheus-operated.monitoring.svc.cluster.local:9090"
                - name: USER_EMAIL
                  value: "test1@example.com"
                - name: USER_PASSWORD
                  value: "password123"
                - name: VALID_PRODUCT_ID
                  value: "1"
                - name: DISABLE_AUTH
                  value: "false"
                - name: TIMEOUT
                  value: "5"
                - name: CHECK_INTERVAL
                  value: "30"
                - name: HOST
                  value: "http://api-gateway.apps.svc.cluster.local:8888"
              volumeMounts:
                - name: locustfile
                  mountPath: /mnt/locust
              resources:
                requests:
                  memory: "1Gi"   # Yêu cầu ít nhất 1Gi RAM
                  cpu: "1000m"  # Yêu cầu ít nhất 1 core CPU
                limits:
                  memory: "2Gi" # Giới hạn tối đa 2GB RAM
                  cpu: "3000m"  # Giới hạn tối đa 3 cores CPU
          restartPolicy: Never
          volumes:
            - name: locustfile
              configMap:
                name: locustfile-18h0h