apiVersion: batch/v1
kind: CronJob
metadata:
  name: locust-0h6h
  namespace: loadtest
spec:
  schedule: "0 0 * * *"   # chạy lúc 00:00 hàng ngày
  timeZone: "Asia/Ho_Chi_Minh"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: locust
              image: locustio/locust:2.31.3
              command: ["locust"]
              args:
                [
                  "-f", "/mnt/locust/locustfile.py",
                  "--headless",
                  "-u", "100", "-r", "10",
                  "--run-time", "6h",
                  "--host", "http://api-gateway.apps.svc.cluster.local:8888"
                ]
              env:
                - name: STOP_HOUR
                  value: "6"
              volumeMounts:
                - name: locustfile
                  mountPath: /mnt/locust
          restartPolicy: Never
          volumes:
            - name: locustfile
              configMap:
                name: locustfile
