apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traffic-pvc
  namespace: loadtest
spec:
  accessModes:
    - ReadWriteMany   # cho phép nhiều pod đọc/ghi
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pvc-copy
  namespace: loadtest
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]  # giữ pod chạy để copy CSV
      volumeMounts:
        - name: traffic-pvc
          mountPath: /mnt/traffic
  volumes:
    - name: traffic-pvc
      persistentVolumeClaim:
        claimName: traffic-pvc
  restartPolicy: Never
---
