server:
  port: 8084

jwt:
  secret: ${JWT_SECRET:esewa}
app:
  jwttoken:
    message: ${APP_JWTTOKEN_MESSAGE:esewa-is-my-secret-key}

spring:
  application:
    name: AUTHENTICATION-SERVICE

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/userdb}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            clientId: 156aaa94354206aa50da
#            clientSecret: abb261ac11ba291f98d84b59f953623bf428095c

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}
    # bật histogram cho http.server.requests
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
