rootUser: admin
rootPassword: admin123

persistence:
  enabled: true
  size: 20Gi
  storageClass: standard   # Minikube

service:
  type: NodePort
  nodePorts:
    api: 30000      # :9000
    console: 30001  # :9001

buckets:           # tạo sẵn bucket
  - name: mlflow
    policy: none
    purge: false
  - name: airflow-logs
    policy: none
    purge: false