apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      serviceAccountName: jenkins-admin
      securityContext:
        fsGroup: 1000
        runAsUser: 1000

      # Nếu volume/permission bị lỗi, initContainer này sẽ giúp sửa quyền
      initContainers:
        - name: init-permissions
          image: busybox:1.36
          command: ["sh", "-c"]
          args:
            - |
              mkdir -p /var/jenkins_home;
              chown -R 1000:1000 /var/jenkins_home;
              chmod -R g+rwX /var/jenkins_home;
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home

      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          resources:
            requests:
              cpu: "500m"
              memory: "500Mi"
            limits:
              cpu: "3000m"
              memory: "5Gi"
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-home
