apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # Nếu cluster KHÔNG có StorageClass mặc định, bạn phải set storageClassName
  # storageClassName: local-path
