apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  selector:
    app: jenkins-server
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 32000
    # Nếu bạn dùng inbound agent (JNLP) thì mở thêm port này
    - name: jnlp
      port: 50000
      targetPort: 50000
      nodePort: 32050
