spring:
  data:
    mongodb:
      database: orderdb
      port: 27017
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:password@localhost:27017/orderdb?authSource=admin}



  application:
    name: ORDER-SERVICE

server:
  port: 8083
