spring:
  data:
    mongodb:
      database: orderdb
      port: 27017
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:password@localhost:27017/orderdb?authSource=admin}



  application:
    name: ORDER-SERVICE

server:
  port: 8083

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}
    # bật histogram cho http.server.requests
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true