---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: apps
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ducanhvo/new-api-gateway:latest
          ports:
            - containerPort: 8888
          env:
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: PRODUCT_SERVICE_URL
            - name: PAYMENT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: PAYMENT_SERVICE_URL
            - name: ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: ORDER_SERVICE_URL
            - name: AUTHENTICATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: AUTHENTICATION_SERVICE_URL
            - name: CHAT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: CHAT_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: apps
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP
