---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  namespace: apps
  labels:
    app: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
        - name: authentication-service
          image: ducanhvo/authentication-service:latest  # đổi đúng tên image
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/userdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: JWT_SECRET
              value: esewa
            - name: APP_JWTTOKEN_MESSAGE
              value: esewa-is-my-secret-key
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: apps
spec:
  selector:
    app: authentication-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: ClusterIP
