---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: apps
  labels:
    app: chat-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: ducanhvo/new-chat-service:latest  # đổi đúng image nếu cần
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://root:password@mongo.infra.svc.cluster.local:27017/chatdb?authSource=admin
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-secret
                  key: api-key
            - name: GEMINI_MODEL
              value: gemini-2.5-flash
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: apps
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: apps
type: Opaque
stringData:
  api-key: "AIzaSyB-Z61gUMYknHhGf1y0HXOaCXDza3ya1tY"
