---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: apps
data:
  PRODUCT_SERVICE_URL: "http://product-service.apps.svc.cluster.local:8081"
  PAYMENT_SERVICE_URL: "http://payment-service.apps.svc.cluster.local:8082"
  ORDER_SERVICE_URL: "http://order-service.apps.svc.cluster.local:8083"
  AUTHENTICATION_SERVICE_URL: "http://authentication-service.apps.svc.cluster.local:8084"
