apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
#      nodeSelector:
#       kubernetes.io/hostname: ip-10-0-102-141.ap-southeast-1.compute.internal
      containers:
        - name: frontend
          image: ducanhvo/new-frontend:latest  # ← Cập nhật tag mới khi cần
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: apps
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
