---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: apps
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ducanhvo/new-order-service:latest  # đổi đúng tên image
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://root:password@mongo.infra.svc.cluster.local:27017/orderdb?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: apps
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
