apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: apps
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3n-m02
      containers:
        - name: order-service
          image: ducanhvo/new-order-service:latest
          ports:
            - name: http
              containerPort: 8083
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://root:password@mongo.infra.svc.cluster.local:27017/orderdb?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: apps
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - name: http
      protocol: TCP
      port: 8083
      targetPort: 8083
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 8083
  type: ClusterIP
