apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: apps
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3n-m02
      containers:
        - name: payment-service
          image: ducanhvo/new-payment-service:latest
          ports:
            - name: http
              containerPort: 8082
          resources:
            requests:
              cpu: "150m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql.infra.svc.cluster.local:3306/paymentdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: apps
  labels:
    app: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - name: http
      protocol: TCP
      port: 8082
      targetPort: 8082
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 8082
  type: ClusterIP
