apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: apps
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3n-m02
      containers:
        - name: product-service
          image: ducanhvo/new-product-service:latest
          ports:
            - name: http
              containerPort: 8081
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.infra.svc.cluster.local:5432/productdb
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: apps
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 8081
  type: ClusterIP
