apiVersion: batch/v1
kind: CronJob
metadata:
  name: bronze-metrics-cronjob
  namespace: cronjob
spec:
  schedule: "*/5 * * * *"
  suspend: true                   # bật lại nếu muốn chạy thật
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: bronze-metrics
              image: python:3.11-slim
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh", "-lc"]
              args:
                - >
                  pip install -q pandas pyarrow requests fsspec s3fs tzdata &&
                  python /app/metrics_dumper.py
              env:
                - name: PROM_URL
                  value: "http://kube-prometheus-kube-prome-prometheus.monitoring.svc.cluster.local:9090"
                - name: S3_BUCKET
                  value: "datalake"
                - name: S3_PREFIX
                  value: "bronze/metrics"
                - name: S3_ENDPOINT
                  value: "https://minio.voducanh.id.vn"   # ✅ dùng HTTPS Cloudflare
                - name: AWS_S3_ADDRESSING_STYLE
                  value: "path"                            # ✅ ép path-style (không wildcard)
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: minio-cred
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: minio-cred
                      key: AWS_SECRET_ACCESS_KEY
                - name: TIMEZONE
                  value: "Asia/Ho_Chi_Minh"
              volumeMounts:
                - name: bronze-script
                  mountPath: /app
                  readOnly: true
          volumes:
            - name: bronze-script
              configMap:
                name: bronze-metrics-script
