CREATE DATABASE IF NOT EXISTS userdb;
CREATE DATABASE IF NOT EXISTS paymentdb;

CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON userdb.* TO 'appuser'@'%';
GRANT ALL PRIVILEGES ON paymentdb.* TO 'appuser'@'%';
