apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: payment-lstm
  namespace: apps
spec:
  scaleTargetRef:
    name: payment-service
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 30
  cooldownPeriod: 60
  advanced:
    restoreToOriginalReplicaCount: false
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.monitoring.svc.cluster.local:9090
        metricName: lstm_desired_replicas
        query: lstm_desired_replicas{service="predictor-exporter-payment"}
        threshold: "1"
  fallback:
    failureThreshold: 3
    replicas: 2
