apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: api-gateway-lstm-scaler
  namespace: apps
spec:
  scaleTargetRef:
    name: api-gateway
  minReplicaCount: 1
  maxReplicaCount: 20
  pollingInterval: 30
  cooldownPeriod: 300

  triggers:
    - type: external
      metadata:
        scalerAddress: predictor-exporter-api-gateway.model.svc.cluster.local:9101
        metricName: lstm_pred_rps_api_gateway
        targetValue: "600"
