sonar.projectKey=payment-service
sonar.projectName=Payment Service
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000
sonar.externalIssuesReportPaths=sonarqube-trivy.json
