# servicemonitor-predictor-exporter.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: predictor-exporter
  namespace: apps
  labels:
    release: kube-prometheus   # giữ trùng Helm release của kube-prometheus-stack
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: predictor-exporter                    # khớp label ở Service phía trên
  namespaceSelector:
    matchNames: ["apps"]
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
