---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: infra
type: Opaque
data:
  postgres_password: cm9vdA==     # base64 của "root"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
  namespace: infra
data:
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS productdb;
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: infra
spec:
  storageClassName: gp2  # nếu dùng local thì bỏ dòng này hoặc dùng "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: infra
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: postgres_password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-initdb-config
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-initdb-config
          configMap:
            name: postgres-initdb-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: infra
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
