spring:
  main:
    web-application-type: reactive
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      # ✅ Bật metrics cho Spring Cloud Gateway
      metrics:
        enabled: true

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods: [GET, POST, DELETE, OPTIONS, PUT, PATCH]
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

      routes:
        - id: PRODUCT-SERVICE
          uri: ${PRODUCT_SERVICE_URL:http://product-service.apps.svc.cluster.local:8081}
          predicates: [ Path=/api/products/** ]

        - id: PAYMENT-SERVICE
          uri: ${PAYMENT_SERVICE_URL:http://payment-service.apps.svc.cluster.local:8082}
          predicates: [ Path=/api/payment/** ]

        - id: ORDER-SERVICE
          uri: ${ORDER_SERVICE_URL:http://order-service.apps.svc.cluster.local:8083}
          predicates: [ Path=/api/order/** ]

        - id: AUTHENTICATION-SERVICE
          uri: ${AUTHENTICATION_SERVICE_URL:http://authentication-service.apps.svc.cluster.local:8084}
          predicates: [ Path=/api/auth/** ]
          
server:
  port: 8888

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true

  #Gắn tag app (lọc/thống kê)
  metrics:
    tags:
      application: ${spring.application.name}
    # bật histogram cho http.server.requests
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
