apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway
  namespace: apps
  labels:
    release: kube-prometheus        # phải trùng tên Helm release kube-prometheus-stack
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: api-gateway         # khớp label ở Service
  namespaceSelector:
    matchNames: ["apps"]
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: authentication-service
  namespace: apps
  labels:
    release: kube-prometheus
spec:
  jobLabel: app
  namespaceSelector:
    matchNames: ["apps"]
  selector:
    matchLabels:
      app: authentication-service
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: order-service
  namespace: apps
  labels:
    release: kube-prometheus
spec:
  jobLabel: app
  namespaceSelector:
    matchNames: ["apps"]
  selector:
    matchLabels:
      app: order-service
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: payment-service
  namespace: apps
  labels:
    release: kube-prometheus
spec:
  jobLabel: app
  namespaceSelector:
    matchNames: ["apps"]
  selector:
    matchLabels:
      app: payment-service
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: product-service
  namespace: apps
  labels:
    release: kube-prometheus
spec:
  jobLabel: app
  namespaceSelector:
    matchNames: ["apps"]
  selector:
    matchLabels:
      app: product-service
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
