apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - --config
            - /etc/cloudflared/config/config.yaml
            - run
            - 356077d4-89e1-41ef-b578-5c8f9df1a790
          volumeMounts:
            - name: cloudflared-config
              mountPath: /etc/cloudflared/config
            - name: cloudflared-credentials
              mountPath: /etc/cloudflared/credentials
              readOnly: true
      volumes:
        - name: cloudflared-config
          configMap:
            name: cloudflared-config
        - name: cloudflared-credentials
          secret:
            secretName: cloudflared-credentials
