# servicemonitor-api-gateway.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway
  namespace: apps
  labels:
    release: monitoring        # phải trùng tên Helm release kube-prometheus-stack
spec:
  jobLabel: app
  selector:
    matchLabels:
      app: api-gateway         # khớp label ở Service
  namespaceSelector:
    matchNames: ["apps"]
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
