sonar.projectKey=authentication-service
sonar.projectName=Authentication Service
sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000
sonar.externalIssuesReportPaths=sonarqube-trivy.json
