spring:
  data:
    mongodb:
      database: chatdb
      port: 27017
      uri: mongodb://localhost:27017

  application:
    name: CHAT-SERVICE

server:
  port: 8085

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

# Cấu hình Gemini API
gemini:
  api-key: AIzaSyBX49M-_XiZpNlEcLVaa__W5rtyJSe6ZIA
  model: gemini-2.5-pro