spring:
  data:
    mongodb:
      database: chatdb
      port: 27017
      uri: mongodb://localhost:27017

  application:
    name: CHAT-SERVICE

server:
  port: 8085

# Gemini API Configuration
gemini:
  api-key: AIzaSyBX49M-_XiZpNlEcLVaa__W5rtyJSe6ZIA
  model: gemini-2.5-flash