# Dùng KubernetesExecutor
executor: KubernetesExecutor

# KHÓA QUAN TRỌNG: tắt Postgres nội bộ của chart
postgresql:
  enabled: false

# Kết nối tới Bitnami Postgres bên ngoài
data:
  metadataConnection:
    user: "airflow"
    pass: "airflowpass"
    protocol: "postgresql"
    host: "airflow-pg-postgresql.ops.svc.cluster.local"
    port: 5432
    db: "airflowdb"

# User admin mặc định
web:
  defaultUser:
    enabled: true
    username: admin
    password: admin

# Secret chứa FERNET KEY (bạn đã tạo)
envFrom:
  - secretRef:
      name: airflow-secrets

# Git-sync DAGs từ repo private
dags:
  gitSync:
    enabled: true
    repo: "https://github.com/voducanh21/Autoscaling-LSTM.git"
    branch: "main"
    subPath: "autoscaling-lstm/data-pipeline/dags"  # ĐÚNG path DAGs trong repo của bạn
    depth: 1
    wait: 60
    credentials:
      usernameSecret:
        name: dags-git-cred
        key: username
      passwordSecret:
        name: dags-git-cred
        key: password

# Tài nguyên nhẹ cho Minikube
scheduler:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

triggerer:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi

webserver:
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

# Ingress
ingress:
  enabled: true
  web:
    path: /
    hosts:
      - airflow.localtest.me
  api:
    enabled: false

# Logs (PVC nhỏ)
logs:
  persistence:
    enabled: true
    size: 2Gi

# Một vài config Airflow
airflow:
  config:
    core:
      load_examples: "False"
    webserver:
      expose_stacktrace: "True"
